package com.mycompany.factory.pattern.observer;

public enum Changes {
    UPDATE_ACCESSORIES_SPEED,
    UPDATE_MOTORS_SPEED,
    UPDATE_BODY_SPEED,
    UPDATE_REQUEST_SPEED,
    START_PRODUCING_AUTO,
    AUTO_SEND,
    BODY_STORAGE_UPDATE,
    BODY_PRODUCED,
    ACCESSORY_STORAGE_UPDATE,
    ACCESSORY_PRODUCED,
    MOTOR_STORAGE_UPDATE,
    MOTOR_PRODUCED,
    AUTO_STORAGE_UPDATE,
    AUTO_PRODUCED
}
